
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.2 EDK_Jm.16
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#define MICROBLAZE_PVR_NONE
